
# Slack Webhook URL to post events from AppD to Slack
# https://hooks.slack.com/services/****/***/*****)
webhookUrl: ""

# (optional) Overrides channel and username configured when creating Webhook (channel: "#random")
# Specify if events to be posted to a different channel and with a different identity.
channel: ""
username: ""

#http timeouts
connectTimeout: 10000
socketTimeout: 10000

#proxy details, provide either proxyUri OR proxyHost and proxyPort.
proxy:
 #host:
 #port:
 uri:
 username:
 password:

